# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install uv
        uv sync
    - name: Package project
      run: |
        zip -r fastapi-app.zip . -x "*.git*" "*.vscode*"  "*__pycache__*" "*.github*" "*.pyc" "venv/*" ".env" ".venv/*" "release/*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fastapi-app
        path: fastapi-app.zip
        retention-days: 30
  deploy:
    runs-on: self-hosted
    needs: build
    environment: prod
    # 只有在主分支 push 时才执行部署
    if: github.ref == 'refs/heads/main'
    
    steps:
      # 下载 build 出来的 zip，指定具体的下载目录避免影响 Runner 根目录
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app
          path: ./deploy-artifact

      # 查看文件（验证是否成功拿到）
      - name: List files
        run: ls -la ./deploy-artifact

      - name: Deploy and Start Server locally
        run: |
          TARGET_DIR=~/www/oauth2-server
          mkdir -p $TARGET_DIR
          
          # 1. 解压最新上传的包直接到目标目录
          unzip -o ./deploy-artifact/fastapi-app.zip -d $TARGET_DIR
          
          # 2. 进入目录并使用 uv 同步依赖
          cd $TARGET_DIR
          uv sync
          
          # 使用 uv 的虚拟环境执行数据库迁移 (如果需要)
          # uv run alembic upgrade head
          
          # 3. 启动或重启服务 (方案C: 使用 pm2)
          pm2 restart oauth2-server || pm2 start ecosystem.config.js
